DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  -- user_id INTEGER REFERENCES users.id NOT NULL,
  order_time TIMESTAMP NOT NULL,
  total_cost INTEGER,
  order_completed BOOLEAN DEFAULT FALSE,
  order_status BOOLEAN DEFAULT FALSE
);
